### ISSUE TITLE
avagraha

### ISSUE THREAD

**Issue by nsesha92** [avinash311/itrans#2]
Hello,

avagraha used to coded for all scripts, but now missing from tamil and grantha

please add .a = avagraha for both

thanks

**Comment by avinash311** [comment]
Tamil does not have a specific code point for avagraha:
https://en.wikipedia.org/wiki/Tamil_(Unicode_block)

Grantha has it: 𑌽 (U+1133D) so will that for Tamil too.

While I've updated the spreadsheet as well the the online page code https://www.aczoom.com/itrans/online/  it may not show up unless the browser re-loads the https://www.aczoom.com/itrans/online/dist/itrans_bundle.js file.
Try F5, browser refresh, or wait a while to make browser fetch the new code.

`ka.a` shows  ` க𑌽 `  for Tamil with this change.

**Comment by nsesha92** [comment]
Thanks a ton, yes, Tamil does not have code point, but Grantha point is
used.

--------------
Warm regards
Seshadri
