### ISSUE TITLE
eEoO coding

### ISSUE THREAD

**Issue by nsesha92** [avinash311/itrans#4]
ITRANS was developed way back in 1991 and is the most popular standard for Indic language transliteration scheme and is a pioneer in this field. Many documents, web pages and Hindi film songbooks in ITRANS format have been created and available.

Many other IMEs and transliteration packages have highly leveraged ITRANS coding scheme, making ITRANS the 'mother' of all Indic transliterators.

Then new revamped itrans/online was released in Sept/Oct 2016, with many innovative features:
-	Supports 15 Indic scripts/languages.
-	Simultaneous output in 3 scripts/languages.
-	User customizable input codes to have one’s own IME character mapping.
-	one and only tool to have a very simple mapping table.  
-	one can add a new language – say German or French. 
-	add a new keyboard mapping - say Hindi Typewriter, Tamilnet99, Inscript, Baraha keyboard layout.

All using a simple xl file, saved and uploaded as a Tab-Separated file.

itrans/online is a transliteration/transcription tool and customizable. However, ITRANS is an ASCII transliteration scheme for Indic scripts and is a STANDARD like IAST, Harvard-Kyoto etc.  ITRANS Transliteration Scheme is used by Itranslator2003, Itranslator9x, sanskritdocuments.org etc. 

The biggest discrepancy in ITRANS is the coding of e, E & o, O:

e = ए (big, deerga, for any Devanagari derived script)
AND
e = எ (small, hrasva for any south Indian script)

However, ए IS NOT equal to எ phonetically, as well as by Unicode code point alignment.
If A=B and A=C, then B should be = C, which is not now.
Because of this grave discrepancy, the Sanskrit version of naalaayira divya prabandam in Vedics.org, srivaishnavam.com are totally wrong, wrt to e/E & o/O. And also, many other sites and printed books. 

Why this #roman AND #roman-south divide? There is nothing like #roman AND #roman-south and the only difference being e/E & o/O. Actually, this column contains ISO 15919 code representation. 

ITRANS was introduced 1991, much before ISO 15919 standard was introduced in 2001. 

My request is to update and make ITRANS coding align with ISO 15919 standard:
https://en.wikipedia.org/wiki/ISO_15919 : - 
- To distinguish between long and short 'e' in Dravidian languages, 'e' now represents ऎ / ॆ (short). 
- To distinguish between long and short 'o' in Dravidian languages, 'o' now represents ऒ / ॊ (short). 
- 
Unicode 14.0, ISO 15919 compliant:
-	Include short e, short o in all supported languages.

Map e = ऎ, E = ए, o = ऒ and O = ओ

-	In non-supported languages map e = E and o = O

This is essential as ALL other IMEs/transliterators have adopted ITRANS scheme. Currently it’s the other way: E = ऎ, e = ए for non-Dravidian languages. Need uniformity / same key sequence for all languages.  

My take, new itrans/online uses updated ITRANS coding that is ISO 15919 compliant while keeping the old 5.3 version, with the same look & feel, still available at the old site for reference/usage of old itx docs – like Itranslator2003 etc that refer to ITRANS coding scheme. 
OR the user modifies the coding in itrans/online for using old itx docs.  (swap e/E, o/O codes)

Also, special character/symbol less codes (ie without symbols like ~n, ^e, ṅ etc)  

My choice, as I had indicated long back:

aa = A
ii = I
uu = U
ee = E  (like a/A, i/I & u/U)
oo = O (like a/A, i/I & u/U)

(people are used to a/A .. etc., so extend the same logic to e&o)

~N = ng
~n = nj = ny
j~n = gn = gy 

ṅ (ng) - is ISO 15919 code.

- divyangjan instead of divya~Njan to get दिव्यङ्जन्‌
- linggaa - instead of li~Ngaa for लिङ्गा 
- gnaan/gyaan instead of j~naan for ञान्
- gnanabhArathi instead of j~nAnabhArati for ज्ञानभारति
- gnAna sanjIvini instead of j~nAna sa~njIvini for ज्ञान सञ्जीविनि

Idea is to avoid special characters, try to make it same as Unicode name, make it the way we 'write' in English and phonetically as close as possible. The old ones for ~na, ~Na, j~n can continue.

Accordingly, I have compiled the attached coding table, by adding (kept the existing mapping for backward compatibility) few more input codes as above and modified e/E & o/O. 

Also added input codes for vedic-tones.

For backward compatibility, I have retained .c for candra. Hence giving .C for candra a, e and o.  

I tested this modified coding, seems to be ok, but for:
1.	x | kSh
2.	GY | j~n | dny | gn | gy
3.	SRI (problem even with default mapping)

[Sesha Itrans IO Table-04Jan22.xlsx](https://github.com/avinash311/itrans/files/7814565/Sesha.Itrans.IO.Table-04Jan22.xlsx)

**Comment by nsesha92** [comment]
In addition:

Periodically I compile/prepare sloka books and need to have/print them in Kannada, Tamil & Sanskrit.

I would prefer typing/loading a file in itrans/online, so that I get my output in all the 3 languages in one go. 

But, due to e/E & o/O mapping discrepancy, I had to do Kannada & Tamil together and separately Sanskrit by replacing
e with ^e, E with e and the same way for o. 

If the ITRANS e/E & o/O coding is made ISO15919 complaint, I can get the desired output in one go.

**Comment by avinash311** [comment]
Since changing the default format for all users will cause existing users to break, the itrans package does offer capability for users to change it as needed , as you mentioned.
https://www.aczoom.com/itrans/online/customize.html

Is that something you cannot use? Since you already have the spreadsheet, looks like you should be able to use a custom spreadsheet on your computers. If the problem is that you have to click on "Load tab-separated itrans data file" each time you visit the online page, that is an issue and unfortunately requires changes to the javascript code to make that easier.

**Comment by nsesha92** [comment]
I very well understand the need for backward compatibility and to those who are used to 5.3 coding schemes like itranslator etc. At the same time, I want to avoid glaring spelling mistakes being made by people. 

It is not just these 4 vowels e, E, o, O, but also the associated CVCs and Conjuncts – (37+3)*4 = 160 letters. 

I am now manually correcting vedics.org’s Sanskrit version of divyaprabandham – 4 volumes of about 300 pages each. Correcting the word file, without affecting the formatting is time-consuming. Nothing can be done to the 1000 sets of printed books with errors and other such books with mistakes. 

Poke-yoke – how to avoid these mistakes and at the same time retain backward compatibility?

https://en.wikipedia.org/wiki/ITRANS 

How to correct this Limitation: Since ITRANS was primarily designed for Sanskrit (and other modern Indo-Aryan languages), it lacks full-coverage for Indic scripts of other languages. Specifically, the support for Dravidian short-vowels 'e' and 'o' is considered ambiguous.

The #roman column actually contains ISO15919 notation. All that I am suggesting is to update ITRANS coding to be ISO15919 compliant so that the above limitation can be addressed. 

As you know, I started using itrans 5.3 back in 2015, and then came this new itrans/online package. I am a little bit tech-savvy, created this custom spreadsheet, and know how to play around with it. But not all are like that, hence these mistake-ridden books and websites. 

Itrans/online package can be made to cater to **BOTH old 5.3 notation as well as new ISO15919** compliant notation by:
-	Either have the old coding scheme at the same old 5.3 site with the same UI. New site uses new coding.
-	Or allow users to “Load” two coding data files – old 5.3 and new ISO15919 coded. 

This I feel will be a win-win situation addressing the ambiguity and the associated mistakes. 

Attaching the updated data file.

[Sesha Itrans IO Table-11Jan22.xlsx](https://github.com/avinash311/itrans/files/7853294/Sesha.Itrans.IO.Table-11Jan22.xlsx)

**Comment by avinash311** [comment]
Those are good points. I would recommend sending me a tab-separated values spreadsheet with the table that works.

I just added a new tsv= feature to the URL that makes loading a new table easier (no need to click on "load" button each time).

Example:
www.aczoom.com/itrans/online/?s=hindi&tsv=https://www.aczoom.com/itrans/online/data/DEFAULT.tsv

If you use Google Docs for your spreadsheet, the https://www.aczoom.com/itrans/online/customize.html explains how to test it automatically.

I can add another .tsv file at the itrans site, so users can visit
www.aczoom.com/itrans/online/?tsv=https://www.aczoom.com/itrans/online/data/ALTERNATE-E-O.tsv
and it will use the new codes.

**Comment by nsesha92** [comment]
Thanks.

I have shared xl file thro google sheets, you can download it.

Also attached here for you to download as xl.

I use Office 365 On Win 10. 
When I choose the option - File-> Save as text (Tab delimited)  (*.txt) file, there is data loss.

ISO 51919 codes like ā, ī saved as a?,  i?. 

I manually edited and corrected the above data loss errors **only for Vowels and checked**.  

I have also added codes in Tamil for RRi, RRI, LLi, LLI, which works ok.

Marked in red are my new additions/suggestions.

As I had mentioned, I have used .c for candra/ardh chandra for backward compatibility.

Also added input codes for vedic tones. 

For all languages, for ksha,  jnya and shrii I have provided command line, for OM Unicode code,  instead of hard code for consistency sake. 

As for this newly added tsv= feature, I am unable to understand it. 

It shows
Loaded: https://www.aczoom.com/itrans/online/data/DEFAULT.tsv 
instead of
Loaded: Default

I need to "click" Load ...file, to upload my customised data file.

And need to click Load Default, to get back to default coding.

[Sesha Itrans IO Table-13Jan22.xlsx](https://github.com/avinash311/itrans/files/7862289/Sesha.Itrans.IO.Table-13Jan22.xlsx)

**Comment by avinash311** [comment]
Thanks for your help on creating the iso based tables. It is now available for use as a default loadable option.
To directly start with ISO encoding and a single output box with hindi: [aczoom.com/itrans/online/?tsv=iso&s=hindi](https://www.aczoom.com/itrans/online/?tsv=iso&s=hindi)

To start with multiple output languages use s=lang1,lang2,lang3 etc

**Comment by nsesha92** [comment]
Thanks a ton for making my request a reality.

I have updated the ITRANS page:

https://en.wikipedia.org/wiki/ITRANS
