### ISSUE TITLE
Using custom tsv file in IBus

### ISSUE THREAD

**Issue by shantanuo** [avinash311/itrans#5]
I am using IBus to type in Marathi using itrans (m17n) keyboard on Ubuntu. There are a lot of characters those are missing or do not match with this online version. I appreciate that you have provided an option to upload .tsv file to modify the layout. But is there any way to use the same .tsv file in IBus?

**Comment by avinash311** [comment]
I very much doubt it - someone who knows IBus would need to create a system like that. Also looks like developing a new keyboard mechanism for Ibus is not trivial, but again, someone who knows that would need to look into that!
