### ISSUE TITLE
ITRANS 5.3, ISO encoding for vedic svaras

### ISSUE THREAD

**Issue by nsesha92** [avinash311/itrans#7]
Hello,

I installed itranslator2003 in my Win10 laptop.

I find that itranslator2003 has defined ITRANS encoding for a few vedic svaras as follows:
(.c candra / ardhachandra was already updated)

\'	udatta-svarita
\_	anudatta
\m+	candrabinduvirama
\'' 	double-svarita 

I have ADDED the above in itrans-iso15919-unicode-mapping table, for backward compatibility and to be consistent with what is stated in  itranslator2003.

Please 'pull' this updated table, so that I can check if it works correctly.

You may also want to add the above in itrans-5.3-unicode-mapping table.

Warm regards
Seshadri
[itranslator2003-itrans encoding.pdf](https://github.com/avinash311/itrans/files/10098171/itranslator2003-itrans.encoding.pdf)

**Comment by nsesha92** [comment]
I modified danda and double danda per itranslator2003 coding for backward compatibility, in ISO coding sheet.
You may also update all the above in Itrans 5.3 coding.

**Comment by avinash311** [comment]
> I modified danda and double danda per itranslator2003 coding for backward compatibility,

I saw there is a backslash in front of the `.`  - is that really in the input - `\.` and `\..`?
It seems there is also `./` and `../'. And `|` and `||` are also accepted it seems.

**Comment by nsesha92** [comment]
As such, . & .. works. 

As I have mentioned, I used itranslator2003 and added/modified SIX input codes with / per it for backward compatibility. 

With this change, . can now be used as such ( instead of -> danda). 
If danda or double danda is required, then \ (escape ) can be used.

**Comment by avinash311** [comment]
Fixed and updated website so https://www.aczoom.com/itrans/online/?tsv=iso  (or clicking on ISO button) will now support the above updates.
